version: "2.2"

services:
  node:
    build: ./docker/dockerfiles/node
    environment:
      AFUP_GLOBAL_MENU_EVENT_LABEL: "Nom Event"
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/data/npm:/.npm
